### ISSUE TITLE
NPE to session factory autowired in AddAccountExample.java.

### ISSUE THREAD

**Issue by CristinaMarilena** [CristinaMarilena/GeneReads#1]

**Comment by ggluta** [comment]
Right, there's your problem. You used `new AddAccountExample()` so the object you've created is not managed by Spring. Therefore, an instance of `SessionFactory` is never injected in the new instance of `AddAccountExample` because it is not owned by Spring, and so they live in different contexts.

**Comment by ggluta** [comment]
Possible fix for new issue at: https://stackoverflow.com/questions/26203446/spring-hibernate-could-not-obtain-transaction-synchronized-session-for-current

**Comment by CristinaMarilena** [comment]
Fixed.
